name: Tests

on:
    push:
        branches:
            - 3.3.x
            - master
            - 'prep-release-*'
        tags:
            - 'release-*'
    pull_request:
        branches:
            - 3.3.x
            - master
            - 'prep-release-*'

jobs:
    # Test with IIS & PostgreSQL on Windows
    windows-tests:
        runs-on: windows-2025
        strategy:
            matrix:
                type: ['unit', 'functional']
                php: ['8.1', '8.2', '8.3']
                db: ['postgres']

        name: Windows - ${{ matrix.type }} - PHP ${{ matrix.php }} - ${{ matrix.db }}

        steps:
            - name: Prepare git for Windows
              run: |
                  git config --system core.autocrlf false
                  git config --system core.eol lf
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, intl, gd, exif, iconv, pgsql, pdo_pgsql, sodium
                  ini-values: upload_tmp_dir=${{ runner.temp }}, sys_temp_dir=${{ runner.temp }}, opcache.enable_cli=1, opcache.enable=1, opcache.jit=1
                  coverage: none

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  cd phpBB
                  echo "dir=$(composer config cache-files-dir)" >> $env:GITHUB_OUTPUT
                  cd ..

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: composer-${{ matrix.php }}-${{ hashFiles('phpBB/composer.lock') }}

            - name: Setup environment for phpBB
              env:
                  GITHUB_WORKSPACE: ${{ github.workspace }}
                  TEMP_DIR: ${{ runner.temp }}
              run: |
                  Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole, IIS-WebServer, IIS-CommonHttpFeatures, IIS-ManagementConsole, IIS-HttpErrors, IIS-HttpRedirect, IIS-WindowsAuthentication, IIS-StaticContent, IIS-DefaultDocument, IIS-HttpCompressionStatic, IIS-DirectoryBrowsing, IIS-WebServerManagementTools, IIS-CGI -All
                  Set-Service wuauserv -StartupType Manual
                  (Get-Content ${env:GITHUB_WORKSPACE}\phpBB\web.config).replace("<configuration>", "<configuration>`n`t<system.web>`n`t`t<customErrors mode=`"Off`"/>`n`t</system.web>") | Set-Content ${env:GITHUB_WORKSPACE}\phpBB\web.config
                  (Get-Content ${env:GITHUB_WORKSPACE}\phpBB\web.config).replace("`t</system.webServer>", "`t`t<httpErrors errorMode=`"Detailed`" />`n`t</system.webServer>") | Set-Content ${env:GITHUB_WORKSPACE}\phpBB\web.config
                  choco install urlrewrite -y
                  Import-Module WebAdministration
                  New-WebSite -Name 'phpBBTest' -PhysicalPath "${env:GITHUB_WORKSPACE}\phpBB" -Force
                  $session = Get-PSSession -Name WinPSCompatSession
                  $sb = {Set-ItemProperty 'IIS:\Sites\phpBBTest' -name Bindings -value @{protocol='http';bindingInformation='*:80:phpbb.test'}}
                  Invoke-Command -Scriptblock $sb -Session $session
                  $sb = {Set-WebConfigurationProperty -filter /system.WebServer/security/authentication/AnonymousAuthentication -name enabled -value true -location "IIS:\Sites\phpBBTest"}
                  Invoke-Command -Scriptblock $sb -Session $session
                  Add-Content -Path $env:windir\System32\drivers\etc\hosts -Value "`r`n127.0.0.1`tphpbb.test" -Force
                  [System.Environment]::SetEnvironmentVariable('PATH',$Env:PATH+";%windir%\system32\inetsrv")
                  echo Setup FAST-CGI configuration
                  Add-WebConfiguration -Filter /system.webServer/fastCgi -PSPath IIS:\ -Value @{fullpath='C:\tools\php\php-cgi.exe';arguments='';idleTimeout=600;activityTimeout=600;requestTimeout=600;instanceMaxRequests=10000;maxInstances=1000;protocol='NamedPipe';flushNamedPipe=$false}
                  echo Setup FACT-CGI handler
                  New-WebHandler -Name "PHP-FastCGI" -Path "*.php" -Modules FastCgiModule -ScriptProcessor 'C:\tools\php\php-cgi.exe' -Verb '*' -ResourceType Either
                  C:\Windows\System32\inetsrv\appcmd set config -section:system.webServer/fastCgi /+"[fullPath='C:\tools\php\php-cgi.exe'].environmentVariables.[name='PHP_FCGI_MAX_REQUESTS',value='10000']" /commit:apphost
                  iisreset
                  NET START W3SVC
                  mkdir "${env:GITHUB_WORKSPACE}\phpBB\cache\test"
                  mkdir "${env:GITHUB_WORKSPACE}\phpBB\cache\installer"
                  icacls "${env:GITHUB_WORKSPACE}\phpBB\cache" /grant Users:F /T
                  icacls "${env:GITHUB_WORKSPACE}\phpBB\files" /grant Users:F /T
                  icacls "${env:GITHUB_WORKSPACE}\phpBB\store" /grant Users:F /T
                  icacls "${env:GITHUB_WORKSPACE}\phpBB\ext" /grant Users:F /T
                  icacls "${env:GITHUB_WORKSPACE}\phpBB\vendor-ext" /grant Users:F /T
                  icacls "${env:GITHUB_WORKSPACE}\phpBB\composer-ext.json" /grant Users:F /T
                  icacls "${env:GITHUB_WORKSPACE}\phpBB\composer-ext.lock" /grant Users:F /T
                  icacls "${env:GITHUB_WORKSPACE}\phpBB\images\avatars\upload" /grant Users:F /T
                  $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("IIS_IUSRS", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
                  $acl = Get-ACL "${env:TEMP_DIR}"
                  $acl.AddAccessRule($accessRule)
                  Set-ACL -Path "${env:TEMP_DIR}" -ACLObject $acl
                  cd ${env:GITHUB_WORKSPACE}\phpBB
                  php ..\composer.phar install
                  cd ..
            - name: Setup database
              run: |
                  $postgreSqlSvc = Get-Service "postgresql*"
                  Set-Service $postgreSqlSvc.Name -StartupType manual
                  $runningStatus = [System.ServiceProcess.ServiceControllerStatus]::Running
                  $maxStartTimeout = New-TimeSpan -Seconds 30
                  try {
                    $postgreSqlSvc.Start()
                    $postgreSqlSvc.WaitForStatus($runningStatus, $maxStartTimeout)
                  } catch  {
                    $_ | select *
                  }
                  [System.Environment]::SetEnvironmentVariable('PATH',$Env:PATH+";${env:PGBIN}")
                  $env:PGPASSWORD = 'root'
                  psql -c 'ALTER SYSTEM SET hot_standby = on;' -U postgres
                  psql -c 'ALTER SYSTEM SET wal_level = minimal;' -U postgres
                  psql -c 'ALTER SYSTEM SET shared_buffers = "6GB";' -U postgres
                  psql -c 'ALTER SYSTEM SET work_mem = "500MB";' -U postgres
                  psql -c 'ALTER SYSTEM SET max_connections = 500;' -U postgres
                  psql -c 'ALTER SYSTEM SET maintenance_work_mem = "1GB";' -U postgres
                  psql -c 'DROP DATABASE IF EXISTS phpbb_tests;' -U postgres
                  psql -c 'create database phpbb_tests;' -U postgres
                  Set-MpPreference -ExclusionPath "${env:PGDATA}" # Exclude PGDATA directory from Windows Defender
                  Set-MpPreference -DisableRealtimeMonitoring $true

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Setup node dependencies
              run: npm ci

            - name: Run unit tests
              if: ${{ matrix.type == 'unit' }}
              run: |
                  phpBB/vendor/bin/phpunit --configuration .github/phpunit-psql-windows-github.xml --display-all-issues --stop-on-error --exclude-group functional,slow
            - name: Run functional tests
              if: ${{ matrix.type == 'functional' }}
              run: |
                  phpBB/vendor/bin/phpunit --configuration .github/phpunit-psql-windows-github.xml --display-all-issues --stop-on-error --group functional
